---
- name: "config: Create an account to be used by Ansible"
  ansible.builtin.user:
    name: "{{ ansible_account_user_name }}"
    comment: "Ansible service account,,,,umask=0077"
    create_home: yes
    home: "{{ ansible_account_home_dir }}"
    password_lock: true
    uid: "{{ ansible_account_uid }}"
    shell: /usr/bin/bash
  register:
    _ansible_user

- name: "config: Create `~/.ssh` directory"
  ansible.builtin.file:
    path: "{{ ansible_account_home_dir }}/.ssh"
    state: directory
    mode: 0700
    owner: "{{ ansible_account_user_name }}"
    group: "{{ _ansible_user['group'] | default(ansible_account_user_name) }}"

- name: "config: Set up `~/.ssh/auhtorized_keys`"
  vars:
    pub_ids: "{{ lookup('pipe','cat ~/.ssh/id_*.pub') | default('') }}"
  ansible.builtin.blockinfile:
    backup: true
    block: |
      {% if pub_ids | length > 1 %}
      {{ pub_ids }}
      {% endif %}
      {% for key in ansible_authorized_keys_extra %}
      {{ key }}
      {% endfor %}
    marker: "# {mark} ANSIBLE MANAGED BLOCK: origin={{ origin }}"
    insertafter: EOF
    create: true
    owner: "{{ ansible_account_user_name }}"
    group: "{{ _ansible_user['group'] | default(ansible_account_user_name) }}"
    mode: 0600
    path: "{{ ansible_account_home_dir }}/.ssh/authorized_keys"

- name: "config: Configure OpenSSH Server"
  ansible.builtin.blockinfile:
    backup: true
    path: "{{ system_sshd_config_file }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: origin={{ origin }}"
    insertafter: EOF
    block: |
      Match Address !{{ ansible_controller_addresses | join(',!') }},!127.0.0.0/8,*
      PubkeyAuthentication yes
      DenyUsers {{ ansible_account_user_name }}
    validate: /usr/sbin/sshd -t -f %s
  notify:
    - "reload sshd"

- name: "config: Enable sudo for Ansible user"
  ansible.builtin.blockinfile:
    backup: true
    path: "{{ system_sudoers_config_file }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: origin={{ origin }}"
    insertafter: EOF
    block: |
      Defaults: {{ ansible_account_user_name }} !requiretty
      {{ ansible_account_user_name }} ALL=(ALL) NOPASSWD: ALL
    validate: /usr/sbin/visudo -csf %s
  when:
  - _system_sudoers_config_file['stat']['exists']
...
