---
- name: "Include distribution specific variables"
  ansible.builtin.include_vars:
    file: "{{ ansible_distribution | lower }}.yaml"
  tags: [always]
  
- import_tasks: "preflight.yaml"
  delegate_to: localhost
  run_once: true

- import_tasks: "packages.yaml"
  become: true

- import_tasks: "account.yaml"
  become: true

- import_tasks: "sshd.yaml"
  become: true

- import_tasks: "sudoers.yaml"
  become: true
...
