---
- name: "sudoers: Enable sudo for Ansible user"
  ansible.builtin.blockinfile:
    backup: true
    path: "{{ system_sudoers_config_file }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: origin={{ origin }}"
    insertafter: EOF
    block: |
      Defaults: {{ ansible_account_user_name }} !requiretty
      {{ ansible_account_user_name }} ALL=(ALL) NOPASSWD: ALL
    validate: /usr/sbin/visudo -csf %s
  when:
  - _system_sudoers_config_file['stat']['exists']
...
