---
- name: "join: Create krb5 configuration directory"
  ansible.builtin.file:
    path: "{{ system_krb5_config_directory }}"
    mode: 0755
    state: directory
  when: _system_krb5_config_directory['stat']['exists'] == false

- name: "join: Create samba configuration directory"
  ansible.builtin.file:
    path: "{{ system_samba_config_directory }}"
    mode: 0755
    state: directory
  when: _system_samba_config_directory['stat']['exists'] == false

- name: "join: Include SSSD krb5 configuration file into the main config"
  ansible.builtin.blockinfile:
    backup: true
    create: true
    marker: "# {mark} ANSIBLE MANAGED BLOCK: origin={{ origin }}"
    insertafter: EOF
    path: "{{ system_krb5_config_file }}"
    block: include {{ sssd_krb5_config_file }}

- name: "join: Include SSSD samba configuration file into the main config"
  ansible.builtin.blockinfile:
    backup: true
    create: true
    marker: "# {mark} ANSIBLE MANAGED BLOCK: origin={{ origin }}"
    insertafter: EOF
    path: "{{ system_samba_config_file }}"
    block: |
      [global]
      include = {{ sssd_samba_config_file }}

- name: "join: Generate SSSD krb5 configuration file"
  ansible.builtin.template:
    backup: true
    src: "./krb5.j2"
    dest: "{{ sssd_krb5_config_file }}"
    mode: "0644"

- name: "join: Generate SSSD samba configuration file"
  ansible.builtin.copy:
    backup: true
    content: |
      realm = {{ ansible_domain | upper }}
      workgroup = {{ ansible_domain | regex_replace('(^.+)\..+','\1') | upper }}
      security = ADS
      kerberos method = secrets and keytab
    dest: "{{ sssd_samba_config_file }}"
    mode: "0644"

- block:
    - name: "join: Join computer to `{{ ansible_domain }}` domain"
      ansible.builtin.command:
        cmd: "/usr/bin/net ads join -U {{ addomain_join_user | quote }}%{{ addomain_join_pass | quote }} osName={{ ansible_distribution }} osVer={{ ansible_distribution_version }}/{{ ansible_distribution_release }}"
      no_log: true
      register: _join_results
  always:
    - name: "join: Unable to join computer to `{{ ansible_domain }}` domain"
      ansible.builtin.debug:
        var: _join_results['stdout']
      when: _join_results['failed']
  when: ansible_check_mode == false
...
