---
- import_tasks: preflight.yaml

- name: "Include distribution specific variables"
  ansible.builtin.include_vars:
    file: "{{ ansible_distribution | lower }}.yaml"
  tags: [always]

- import_tasks: packages.yaml
  become: true

- import_tasks: join.yaml
  become: true

- import_tasks: config.yaml
  become: true

- import_tasks: undo.yaml
  become: true
  tags: [never, undo]
...
