---
- name: "packages: Install packages (APT)"
  ansible.builtin.apt:
    name: "{{ packages_install }}"
    state: present
    update_cache: true
    update_cache_retries: 2
    update_cache_retry_max_delay: 5
    cache_valid_time: 3600
  when:
    - (ansible_pkg_mgr | lower) == 'apt'
...
