---
- name: "packages: Install packages (Debian)"
  ansible.builtin.apt:
    name: "{{ packages_install }}"
    state: present
    update_cache: yes
  when:
    - (ansible_os_family | lower) == 'debian'
...
