---
- name: "config: Create krb5 configuration directory"
  ansible.builtin.file:
    path: "{{ system_krb5_config_directory }}"
    mode: 0755
    state: directory
  when: _system_krb5_config_directory['stat']['exists'] == false

- name: "config: Create samba configuration directory"
  ansible.builtin.file:
    path: "{{ system_samba_config_directory }}"
    mode: 0755
    state: directory
  when: _system_samba_config_directory['stat']['exists'] == false

- name: "config: Include SSSD krb5 configuration file into the main config"
  ansible.builtin.blockinfile:
    backup: true
    create: true
    marker: "# {mark} ANSIBLE MANAGED BLOCK: origin={{ origin }}"
    insertafter: EOF
    path: "{{ system_krb5_config_file }}"
    block: include {{ sssd_krb5_config_file }}

- name: "config: Include SSSD samba configuration file into the main config"
  ansible.builtin.blockinfile:
    backup: true
    create: true
    marker: "# {mark} ANSIBLE MANAGED BLOCK: origin={{ origin }}"
    insertafter: EOF
    path: "{{ system_samba_config_file }}"
    block: |
      [global]
      include = {{ sssd_samba_config_file }}

- name: "config: Generate SSSD krb5 configuration file"
  ansible.builtin.template:
    backup: true
    src: "./krb5.j2"
    dest: "{{ sssd_krb5_config_file }}"
    mode: "0644"

- name: "config: Generate SSSD samba configuration file"
  ansible.builtin.copy:
    backup: true
    content: |
      realm = {{ ansible_domain | upper }}
      workgroup = {{ ansible_domain | regex_replace('(^.+)\..+','\1') | upper }}
      security = ADS
      kerberos method = secrets and keytab
    dest: "{{ sssd_samba_config_file }}"
    mode: "0644"

- block:
    - name: "config: Join computer to `{{ ansible_domain }}` domain"
      ansible.builtin.command:
        cmd: "/usr/bin/net ads join -U {{ ad_member_join_user | quote }}%{{ ad_member_join_pass | quote }} osName={{ ansible_distribution }} osVer={{ ansible_distribution_version }}/{{ ansible_distribution_release }}"
      no_log: true
      register: _join_results
  always:
    - name: "config: Unable to join computer to `{{ ansible_domain }}` domain"
      ansible.builtin.debug:
        var: _join_results['stdout']
      when: _join_results['failed']
  when: ansible_check_mode == false

- name: "config: Create SSSD configuration directory"
  ansible.builtin.file:
    path: "{{ system_sssd_config_directory }}"
    mode: 0755
    state: directory
  when: _system_sssd_config_directory['stat']['exists'] == false

- name: "config: Generate SSSD service configuration file"
  ansible.builtin.template:
    backup: yes
    src: "./sssd.j2"
    dest: "{{ system_sssd_config_file }}"
    mode: "0600"
  notify: "restart sssd"

- name: "config: Create SSSD logrotate configuration file"
  ansible.builtin.template:
    backup: true
    src: "./logrotate.j2"
    dest: "{{ sssd_logrotate_config_file }}"
  when:
  - _system_logrotate_config_file['stat']['exists']
  - _system_logrotate_config_directory['stat']['exists']

- name: "config: Enable PAM mkhomedir"
  ansible.builtin.lineinfile:
    backup: yes
    line: "session optional {{ pam_mkhomedir_module_name }} umask=0077"
    path: "{{ pam_common_session_file }}"
    regexp: '^session[\ \t]+.*{{ pam_mkhomedir_module_name }}.*'

- name: "config: Enable sudo for `sssd_allow_groups`"
  ansible.builtin.blockinfile:
    backup: true
    path: "{{ system_sudoers_config_file }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: origin={{ origin }}"
    insertafter: EOF
    block: |
      {% for a in sssd_allow_groups %}
      %{{ a | replace(" ","\ ") }} ALL=(ALL:ALL) ALL
      {% endfor %}
    validate: /usr/sbin/visudo -csf %s
  when:
  - _system_sudoers_config_file['stat']['exists']

- name: "config: Enable SSSD service"
  ansible.builtin.service:
    name: "{{ sssd_service_name }}"
    enabled: yes
  when: ansible_check_mode == false
...
