---
- block:
    - name: "undo: Leave the `{{ ansible_domain }}` domain"
      ansible.builtin.command:
        cmd: "/usr/bin/net ads leave -U {{ ad_member_join_user | quote }}%{{ ad_member_join_pass | quote }}"
      no_log: true
      register: _leave_results
      when: ansible_check_mode == false
  rescue:
    - meta: noop
  always:
    - name: "undo: Unable to leave from `{{ ansible_domain }}` domain"
      ansible.builtin.debug:
        var: _leave_results['stdout']
      when:
      - ansible_check_mode == false
      - _leave_results['failed']

- name: "undo: Exclude SSSD krb5 config file from the main config"
  ansible.builtin.blockinfile:
    backup: true
    create: false
    marker: "# {mark} ANSIBLE MANAGED BLOCK: origin={{ origin }}"
    path: "{{ system_krb5_config_file }}"
    state: absent
  ignore_errors: true

- name: "undo: Exclude SSSD samba config file from the main config"
  ansible.builtin.blockinfile:
    backup: true
    create: false
    marker: "# {mark} ANSIBLE MANAGED BLOCK: origin={{ origin }}"
    path: "{{ system_samba_config_file }}"
    state: absent
  ignore_errors: true

- name: "undo: Delete SSSD krb5 configuration file"
  ansible.builtin.file:
    path: "{{ sssd_krb5_config_file }}"
    state: absent

- name: "undo: Delete SSSD samba configuration file"
  ansible.builtin.file:
    path: "{{ sssd_samba_config_file }}"
    state: absent

- name: "undo: Delete SSSD logrotate configuration file"
  ansible.builtin.file:
    path: "{{ sssd_logrotate_config_file }}"
    state: absent

- name: "undo: Remove SSSD sudo configuration block"
  ansible.builtin.blockinfile:
    backup: true
    path: "{{ system_sudoers_config_file }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: origin={{ origin }}"
    state: absent
    validate: /usr/sbin/visudo -csf %s
  when:
  - _system_sudoers_config_file['stat']['exists']

- name: "undo: Delete SSSD configuration file"
  ansible.builtin.file:
    path: "{{ system_sssd_config_file }}"
    state: absent
...
