---
- block:
  - name: "undo: APT: Uninstall packages"
    ansible.builtin.apt:
      name: "{{ packages_install }}"
      state: absent
      update_cache: no
      purge: true
      autoremove: true
  - name: "undo: APT: Remove repository file"
    ansible.builtin.file:
      dest: "{{ apt_sources_list_d }}/zabbix-{{ zabbix_agent_version }}.list"
      state: absent
  - name: "undo: APT: Remove trusted GPG keys"
    ansible.builtin.file:
      dest: "{{ apt_trusted_gpg_d }}/{{ item.split('/')[-1] }}"
      state: absent
    loop: "{{ lookup('fileglob', 'apt_trusted_gpg_d/*', wantlist=True) }}" 
  when: (ansible_pkg_mgr | lower) == 'apt'

- name: "undo: Delete configuration root"
  ansible.builtin.file:
    dest: "{{ zabbix_agent_config_root }}"
    state: absent

- name: "undo: Delete logrotate configuration snippet"
  ansible.builtin.file:
    dest: "{{ zabbix_agent_logrotate_config_snippet }}"
    state: absent

- name: "undo: Delete sudoers configuration snippet"
  ansible.builtin.file:
    dest: "{{ zabbix_agent_sudoers_config_snippet }}"
    state: absent

- name: "undo: Remove Zabbix Agent user account"
  ansible.builtin.user:
    name: "{{ zabbix_agent_user }}"
    state: absent
    remove: true
    force: true

- name: "undo: Remove Zabbix Agent user group"
  ansible.builtin.group:
    name: "{{ zabbix_agent_group }}"
    state: absent
...
