---
- name: "Restart vsFTPd service"
  become: true
  ansible.builtin.service:
    name: "{{ vsftpd_service_name }}"
    state: restarted
  listen: "restart vsftpd"
  when: ansible_check_mode == false

- name: "Restart OpenSSH Server"
  become: true
  ansible.builtin.service:
    name: "{{ sshd_service_name }}"
    state: restarted
  listen: "restart sshd"
  when: ansible_check_mode == false

- name: "Restart Rsyslog service"
  become: true
  ansible.builtin.service:
    name: "{{ rsyslog_service_name }}"
    state: restarted
  listen: "restart rsyslog"
  when: ansible_check_mode == false
...
