---
- name: "Does `{{ system_logrotate_config_file }}` exist?"
  stat:
    path: "{{ system_logrotate_config_file }}"
  register: _system_logrotate_config_file

- name: "Does `{{ system_logrotate_config_directory }}` exist?"
  stat:
    path: "{{ system_logrotate_config_directory }}"
  register: _system_logrotate_config_directory
  when: _system_logrotate_config_file['stat']['exists']

- name: "Does `{{ system_rsyslog_config_file }}` exist?"
  stat:
    path: "{{ system_rsyslog_config_file }}"
  register: _system_rsyslog_config_file

- name: "Does `{{ system_rsyslog_config_directory }}` exist?"
  stat:
    path: "{{ system_rsyslog_config_directory }}"
  register: _system_rsyslog_config_directory
  when: _system_rsyslog_config_file['stat']['exists']

- name: "Does `{{ system_sudoers_config_file }}` exist?"
  stat:
    path: "{{ system_sudoers_config_file }}"
  register: _system_sudoers_config_file

- name: "Does `{{ system_sudoers_config_directory }}` exist?"
  stat:
    path: "{{ system_sudoers_config_directory }}"
  register: _system_sudoers_config_directory
  when: _system_sudoers_config_file['stat']['exists']
...
